# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('date', models.DateField(verbose_name='date')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='maximum file size 10.0\xa0MB', upload_to=gallery.models.photo_location, verbose_name='Image')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.Album', verbose_name='album')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
